runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /tokensignin
  script: tokensignin.app
- url: /signout
  script: tokensignin.app
- url: /anotherPage
  script: anotherPage.app
- url: /
  script: login.app
